"""empty message

Revision ID: 14566c55f6b0
Revises: 
Create Date: 2021-02-07 01:32:16.041781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14566c55f6b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomedaequipe', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomedaequipe')
    )
    op.create_table('novas_desovas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('praia', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('monitoramento', sa.String(length=3), nullable=True),
    sa.Column('datadoalerta', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tartarugas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anilha', sa.String(), nullable=True),
    sa.Column('informacoes', sa.Text(), nullable=True),
    sa.Column('especie', sa.String(), nullable=True),
    sa.Column('tipo_de_registro', sa.String(), nullable=True),
    sa.Column('monitoramento', sa.String(length=3), nullable=True),
    sa.Column('sexo', sa.String(length=2), nullable=True),
    sa.Column('ccc', sa.String(length=5), nullable=True),
    sa.Column('lcc', sa.String(length=5), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('praia', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('datadoalerta', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tartarugas')
    op.drop_table('novas_desovas')
    op.drop_table('equipe')
    # ### end Alembic commands ###
