"""empty message

Revision ID: 3fd3fc52dc02
Revises: 
Create Date: 2021-01-16 01:42:27.257652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd3fc52dc02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lideres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pesquisadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomedaequipe', sa.String(), nullable=True),
    sa.Column('lider_id', sa.Integer(), nullable=True),
    sa.Column('pesquisador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lider_id'], ['lideres.id'], ),
    sa.ForeignKeyConstraint(['pesquisador_id'], ['pesquisadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lider_id'),
    sa.UniqueConstraint('nomedaequipe'),
    sa.UniqueConstraint('pesquisador_id')
    )
    op.create_table('novas_desovas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('praia', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('monitoramento', sa.String(length=3), nullable=True),
    sa.Column('equipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipe_id')
    )
    op.create_table('tartarugas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anilha', sa.String(), nullable=True),
    sa.Column('especie', sa.String(), nullable=True),
    sa.Column('tipo_de_registro', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(length=2), nullable=True),
    sa.Column('ccc', sa.String(length=5), nullable=True),
    sa.Column('lcc', sa.String(length=5), nullable=True),
    sa.Column('informacoes', sa.Text(), nullable=True),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('praia', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('monitoramento', sa.String(length=3), nullable=True),
    sa.Column('equipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anilha'),
    sa.UniqueConstraint('equipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tartarugas')
    op.drop_table('novas_desovas')
    op.drop_table('equipes')
    op.drop_table('pesquisadores')
    op.drop_table('lideres')
    # ### end Alembic commands ###
